# Generated by Django 3.2.8 on 2022-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
