# Generated by Django 3.2.8 on 2022-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurents', '0003_rename_password2_newuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurants_name', models.CharField(max_length=150, unique=True)),
                ('restaurants_location', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
