# Generated by Django 4.1 on 2022-08-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurents", "0005_customaccountmanager_otp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otp",
            old_name="otp",
            new_name="otpdata",
        ),
    ]
