# Generated by Django 4.1 on 2022-08-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurents", "0007_delete_customaccountmanager_newuser_groups_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newuser",
            old_name="user_name",
            new_name="username",
        ),
    ]
